docker: explicitly specify alpine base version
Allows to avoid the following error:
```
Step 8/16 : RUN apk add --no-cache iproute2-tc
 ---> Running in b5a7adc54072
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  iproute2-tc (missing):
    required by: world[iproute2-tc]
The command '/bin/sh -c apk add --no-cache iproute2-tc' returned a non-zero code: 1
```